org: rdiao
app: harold
service: harold-question-bot

provider:
  name: aws
  runtime: nodejs10.x
  profile: default

functions:
  cron:
    handler: handler.run
    events:
      # Lambda is deployed in Virgina AZ - so time needs to be correct for AU timezone:
      - schedule: cron(15 23 ? * SUN-THU *)
